name: gallery_two
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  camera: ^0.11.4
  easy_image_viewer: ^1.5.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  image: ^4.8.0
  intl: ^0.20.2
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  simple_animations: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true